sources:


  - name: airbnb
    database: racko-master-project-505113
    schema: airbnb_raw
    
    tables: 
      - name: hosts 
        identifier: raw_hosts
        columns: 
          - name: ID
            description: "This is column_id"
          - name: name 
            description: "This is column name"
            

      - name: reviews 
        identifier: raw_reviews
        columns: 
          - name: listing_id
            description: "This is Listing_id"
          - name: Date 
            description: "This is the date"

      - name: listings 
        identifier: raw_listings
        columns: 
          - name: id
            description: "This is Listing_id"
          - name: listing_url 
            description: "This is the listing url"


  - name: airbnb_2
    database: racko-master-project-505113
    schema: "{{env_var('AIRBNB_TARGET_SCHEMA')}}"
    
    tables: 
      - name: new_hosts
        identifier: AIRBNB_TESTS_HOSTS
        columns: 
          - name: ID
            description: "This is column_id"
          - name: name 
            description: "This is column name"

